package Futronic.openFinger;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fingerprint.proto

public final class FingerprintOuterClass {
  private FingerprintOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FingerprintOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Fingerprint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <pre>
     * 500 ppi or 1000 ppi
     * </pre>
     *
     * <code>int32 resolution = 3;</code>
     * @return The resolution.
     */
    int getResolution();

    /**
     * <code>.Fingerprint.Colorspace color = 4;</code>
     * @return The enum numeric value on the wire for color.
     */
    int getColorValue();
    /**
     * <code>.Fingerprint.Colorspace color = 4;</code>
     * @return The color.
     */
    FingerprintOuterClass.Fingerprint.Colorspace getColor();

    /**
     * <pre>
     * image data
     * </pre>
     *
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * message specifying the fingerprint image
   * </pre>
   *
   * Protobuf type {@code Fingerprint}
   */
  public static final class Fingerprint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Fingerprint)
      FingerprintOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Fingerprint.newBuilder() to construct.
    private Fingerprint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Fingerprint() {
      color_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Fingerprint();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Fingerprint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              width_ = input.readInt32();
              break;
            }
            case 16: {

              height_ = input.readInt32();
              break;
            }
            case 24: {

              resolution_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              color_ = rawValue;
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FingerprintOuterClass.internal_static_Fingerprint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FingerprintOuterClass.internal_static_Fingerprint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FingerprintOuterClass.Fingerprint.class, FingerprintOuterClass.Fingerprint.Builder.class);
    }

    /**
     * <pre>
     * informs about the image color space
     * </pre>
     *
     * Protobuf enum {@code Fingerprint.Colorspace}
     */
    public enum Colorspace
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GRAYSCALE = 0;</code>
       */
      GRAYSCALE(0),
      /**
       * <code>RGB = 1;</code>
       */
      RGB(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GRAYSCALE = 0;</code>
       */
      public static final int GRAYSCALE_VALUE = 0;
      /**
       * <code>RGB = 1;</code>
       */
      public static final int RGB_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Colorspace valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Colorspace forNumber(int value) {
        switch (value) {
          case 0: return GRAYSCALE;
          case 1: return RGB;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Colorspace>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Colorspace> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Colorspace>() {
              public Colorspace findValueByNumber(int number) {
                return Colorspace.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return FingerprintOuterClass.Fingerprint.getDescriptor().getEnumTypes().get(0);
      }

      private static final Colorspace[] VALUES = values();

      public static Colorspace valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Colorspace(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Fingerprint.Colorspace)
    }

    public static final int WIDTH_FIELD_NUMBER = 1;
    private int width_;
    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int RESOLUTION_FIELD_NUMBER = 3;
    private int resolution_;
    /**
     * <pre>
     * 500 ppi or 1000 ppi
     * </pre>
     *
     * <code>int32 resolution = 3;</code>
     * @return The resolution.
     */
    @java.lang.Override
    public int getResolution() {
      return resolution_;
    }

    public static final int COLOR_FIELD_NUMBER = 4;
    private int color_;
    /**
     * <code>.Fingerprint.Colorspace color = 4;</code>
     * @return The enum numeric value on the wire for color.
     */
    @java.lang.Override public int getColorValue() {
      return color_;
    }
    /**
     * <code>.Fingerprint.Colorspace color = 4;</code>
     * @return The color.
     */
    @java.lang.Override public FingerprintOuterClass.Fingerprint.Colorspace getColor() {
      @SuppressWarnings("deprecation")
      FingerprintOuterClass.Fingerprint.Colorspace result = FingerprintOuterClass.Fingerprint.Colorspace.valueOf(color_);
      return result == null ? FingerprintOuterClass.Fingerprint.Colorspace.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * image data
     * </pre>
     *
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (width_ != 0) {
        output.writeInt32(1, width_);
      }
      if (height_ != 0) {
        output.writeInt32(2, height_);
      }
      if (resolution_ != 0) {
        output.writeInt32(3, resolution_);
      }
      if (color_ != FingerprintOuterClass.Fingerprint.Colorspace.GRAYSCALE.getNumber()) {
        output.writeEnum(4, color_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (resolution_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resolution_);
      }
      if (color_ != FingerprintOuterClass.Fingerprint.Colorspace.GRAYSCALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, color_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FingerprintOuterClass.Fingerprint)) {
        return super.equals(obj);
      }
      FingerprintOuterClass.Fingerprint other = (FingerprintOuterClass.Fingerprint) obj;

      if (getWidth()
          != other.getWidth()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getResolution()
          != other.getResolution()) return false;
      if (color_ != other.color_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + RESOLUTION_FIELD_NUMBER;
      hash = (53 * hash) + getResolution();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + color_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FingerprintOuterClass.Fingerprint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FingerprintOuterClass.Fingerprint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FingerprintOuterClass.Fingerprint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FingerprintOuterClass.Fingerprint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FingerprintOuterClass.Fingerprint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message specifying the fingerprint image
     * </pre>
     *
     * Protobuf type {@code Fingerprint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Fingerprint)
        FingerprintOuterClass.FingerprintOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FingerprintOuterClass.internal_static_Fingerprint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FingerprintOuterClass.internal_static_Fingerprint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FingerprintOuterClass.Fingerprint.class, FingerprintOuterClass.Fingerprint.Builder.class);
      }

      // Construct using Futronic.openFinger.FingerprintOuterClass.Fingerprint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        width_ = 0;

        height_ = 0;

        resolution_ = 0;

        color_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FingerprintOuterClass.internal_static_Fingerprint_descriptor;
      }

      @java.lang.Override
      public FingerprintOuterClass.Fingerprint getDefaultInstanceForType() {
        return FingerprintOuterClass.Fingerprint.getDefaultInstance();
      }

      @java.lang.Override
      public FingerprintOuterClass.Fingerprint build() {
        FingerprintOuterClass.Fingerprint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FingerprintOuterClass.Fingerprint buildPartial() {
        FingerprintOuterClass.Fingerprint result = new FingerprintOuterClass.Fingerprint(this);
        result.width_ = width_;
        result.height_ = height_;
        result.resolution_ = resolution_;
        result.color_ = color_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FingerprintOuterClass.Fingerprint) {
          return mergeFrom((FingerprintOuterClass.Fingerprint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FingerprintOuterClass.Fingerprint other) {
        if (other == FingerprintOuterClass.Fingerprint.getDefaultInstance()) return this;
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getResolution() != 0) {
          setResolution(other.getResolution());
        }
        if (other.color_ != 0) {
          setColorValue(other.getColorValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FingerprintOuterClass.Fingerprint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FingerprintOuterClass.Fingerprint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int width_ ;
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 width = 1;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 width = 1;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 width = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 height = 2;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 height = 2;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 height = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int resolution_ ;
      /**
       * <pre>
       * 500 ppi or 1000 ppi
       * </pre>
       *
       * <code>int32 resolution = 3;</code>
       * @return The resolution.
       */
      @java.lang.Override
      public int getResolution() {
        return resolution_;
      }
      /**
       * <pre>
       * 500 ppi or 1000 ppi
       * </pre>
       *
       * <code>int32 resolution = 3;</code>
       * @param value The resolution to set.
       * @return This builder for chaining.
       */
      public Builder setResolution(int value) {
        
        resolution_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 500 ppi or 1000 ppi
       * </pre>
       *
       * <code>int32 resolution = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResolution() {
        
        resolution_ = 0;
        onChanged();
        return this;
      }

      private int color_ = 0;
      /**
       * <code>.Fingerprint.Colorspace color = 4;</code>
       * @return The enum numeric value on the wire for color.
       */
      @java.lang.Override public int getColorValue() {
        return color_;
      }
      /**
       * <code>.Fingerprint.Colorspace color = 4;</code>
       * @param value The enum numeric value on the wire for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorValue(int value) {
        
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Fingerprint.Colorspace color = 4;</code>
       * @return The color.
       */
      @java.lang.Override
      public FingerprintOuterClass.Fingerprint.Colorspace getColor() {
        @SuppressWarnings("deprecation")
        FingerprintOuterClass.Fingerprint.Colorspace result = FingerprintOuterClass.Fingerprint.Colorspace.valueOf(color_);
        return result == null ? FingerprintOuterClass.Fingerprint.Colorspace.UNRECOGNIZED : result;
      }
      /**
       * <code>.Fingerprint.Colorspace color = 4;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(FingerprintOuterClass.Fingerprint.Colorspace value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        color_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Fingerprint.Colorspace color = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        
        color_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * image data
       * </pre>
       *
       * <code>bytes data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * image data
       * </pre>
       *
       * <code>bytes data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * image data
       * </pre>
       *
       * <code>bytes data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Fingerprint)
    }

    // @@protoc_insertion_point(class_scope:Fingerprint)
    private static final FingerprintOuterClass.Fingerprint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FingerprintOuterClass.Fingerprint();
    }

    public static FingerprintOuterClass.Fingerprint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Fingerprint>
        PARSER = new com.google.protobuf.AbstractParser<Fingerprint>() {
      @java.lang.Override
      public Fingerprint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Fingerprint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Fingerprint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Fingerprint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FingerprintOuterClass.Fingerprint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Fingerprint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Fingerprint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Fingerprint.proto\"\234\001\n\013Fingerprint\022\r\n\005w" +
      "idth\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\022\022\n\nresolution" +
      "\030\003 \001(\005\022&\n\005color\030\004 \001(\0162\027.Fingerprint.Colo" +
      "rspace\022\014\n\004data\030\005 \001(\014\"$\n\nColorspace\022\r\n\tGR" +
      "AYSCALE\020\000\022\007\n\003RGB\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Fingerprint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Fingerprint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Fingerprint_descriptor,
        new java.lang.String[] { "Width", "Height", "Resolution", "Color", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
