package Futronic.openFinger;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Level2.proto

public final class Level2OuterClass {
  private Level2OuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface Level2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:Level2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    int getY();

    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>float angle = 4;</code>
     * @return The angle.
     */
    float getAngle();

    /**
     * <code>int32 quality = 5;</code>
     * @return The quality.
     */
    int getQuality();

    /**
     * <code>int32 img_width = 6;</code>
     * @return The imgWidth.
     */
    int getImgWidth();

    /**
     * <code>int32 img_height = 7;</code>
     * @return The imgHeight.
     */
    int getImgHeight();
  }
  /**
   * Protobuf type {@code Level2}
   */
  public static final class Level2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Level2)
      Level2OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Level2.newBuilder() to construct.
    private Level2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Level2() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Level2();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Level2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
            case 24: {

              type_ = input.readInt32();
              break;
            }
            case 37: {

              angle_ = input.readFloat();
              break;
            }
            case 40: {

              quality_ = input.readInt32();
              break;
            }
            case 48: {

              imgWidth_ = input.readInt32();
              break;
            }
            case 56: {

              imgHeight_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Level2OuterClass.internal_static_Level2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Level2OuterClass.internal_static_Level2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Level2OuterClass.Level2.class, Level2OuterClass.Level2.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>int32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>int32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>int32 type = 3;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int ANGLE_FIELD_NUMBER = 4;
    private float angle_;
    /**
     * <code>float angle = 4;</code>
     * @return The angle.
     */
    @java.lang.Override
    public float getAngle() {
      return angle_;
    }

    public static final int QUALITY_FIELD_NUMBER = 5;
    private int quality_;
    /**
     * <code>int32 quality = 5;</code>
     * @return The quality.
     */
    @java.lang.Override
    public int getQuality() {
      return quality_;
    }

    public static final int IMG_WIDTH_FIELD_NUMBER = 6;
    private int imgWidth_;
    /**
     * <code>int32 img_width = 6;</code>
     * @return The imgWidth.
     */
    @java.lang.Override
    public int getImgWidth() {
      return imgWidth_;
    }

    public static final int IMG_HEIGHT_FIELD_NUMBER = 7;
    private int imgHeight_;
    /**
     * <code>int32 img_height = 7;</code>
     * @return The imgHeight.
     */
    @java.lang.Override
    public int getImgHeight() {
      return imgHeight_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
      if (type_ != 0) {
        output.writeInt32(3, type_);
      }
      if (angle_ != 0F) {
        output.writeFloat(4, angle_);
      }
      if (quality_ != 0) {
        output.writeInt32(5, quality_);
      }
      if (imgWidth_ != 0) {
        output.writeInt32(6, imgWidth_);
      }
      if (imgHeight_ != 0) {
        output.writeInt32(7, imgHeight_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (angle_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, angle_);
      }
      if (quality_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quality_);
      }
      if (imgWidth_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, imgWidth_);
      }
      if (imgHeight_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, imgHeight_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Level2OuterClass.Level2)) {
        return super.equals(obj);
      }
      Level2OuterClass.Level2 other = (Level2OuterClass.Level2) obj;

      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (getType()
          != other.getType()) return false;
      if (java.lang.Float.floatToIntBits(getAngle())
          != java.lang.Float.floatToIntBits(
              other.getAngle())) return false;
      if (getQuality()
          != other.getQuality()) return false;
      if (getImgWidth()
          != other.getImgWidth()) return false;
      if (getImgHeight()
          != other.getImgHeight()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + ANGLE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAngle());
      hash = (37 * hash) + QUALITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuality();
      hash = (37 * hash) + IMG_WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getImgWidth();
      hash = (37 * hash) + IMG_HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getImgHeight();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Level2OuterClass.Level2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Level2OuterClass.Level2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Level2OuterClass.Level2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Level2OuterClass.Level2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Level2OuterClass.Level2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Level2OuterClass.Level2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Level2OuterClass.Level2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Level2OuterClass.Level2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Level2OuterClass.Level2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Level2OuterClass.Level2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Level2OuterClass.Level2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Level2OuterClass.Level2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Level2OuterClass.Level2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Level2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Level2)
        Level2OuterClass.Level2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Level2OuterClass.internal_static_Level2_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Level2OuterClass.internal_static_Level2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Level2OuterClass.Level2.class, Level2OuterClass.Level2.Builder.class);
      }

      // Construct using Futronic.openFinger.Level2OuterClass.Level2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        type_ = 0;

        angle_ = 0F;

        quality_ = 0;

        imgWidth_ = 0;

        imgHeight_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Level2OuterClass.internal_static_Level2_descriptor;
      }

      @java.lang.Override
      public Level2OuterClass.Level2 getDefaultInstanceForType() {
        return Level2OuterClass.Level2.getDefaultInstance();
      }

      @java.lang.Override
      public Level2OuterClass.Level2 build() {
        Level2OuterClass.Level2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Level2OuterClass.Level2 buildPartial() {
        Level2OuterClass.Level2 result = new Level2OuterClass.Level2(this);
        result.x_ = x_;
        result.y_ = y_;
        result.type_ = type_;
        result.angle_ = angle_;
        result.quality_ = quality_;
        result.imgWidth_ = imgWidth_;
        result.imgHeight_ = imgHeight_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Level2OuterClass.Level2) {
          return mergeFrom((Level2OuterClass.Level2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Level2OuterClass.Level2 other) {
        if (other == Level2OuterClass.Level2.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getAngle() != 0F) {
          setAngle(other.getAngle());
        }
        if (other.getQuality() != 0) {
          setQuality(other.getQuality());
        }
        if (other.getImgWidth() != 0) {
          setImgWidth(other.getImgWidth());
        }
        if (other.getImgHeight() != 0) {
          setImgHeight(other.getImgHeight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Level2OuterClass.Level2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Level2OuterClass.Level2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>int32 x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public int getX() {
        return x_;
      }
      /**
       * <code>int32 x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>int32 y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public int getY() {
        return y_;
      }
      /**
       * <code>int32 y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 3;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private float angle_ ;
      /**
       * <code>float angle = 4;</code>
       * @return The angle.
       */
      @java.lang.Override
      public float getAngle() {
        return angle_;
      }
      /**
       * <code>float angle = 4;</code>
       * @param value The angle to set.
       * @return This builder for chaining.
       */
      public Builder setAngle(float value) {
        
        angle_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float angle = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAngle() {
        
        angle_ = 0F;
        onChanged();
        return this;
      }

      private int quality_ ;
      /**
       * <code>int32 quality = 5;</code>
       * @return The quality.
       */
      @java.lang.Override
      public int getQuality() {
        return quality_;
      }
      /**
       * <code>int32 quality = 5;</code>
       * @param value The quality to set.
       * @return This builder for chaining.
       */
      public Builder setQuality(int value) {
        
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quality = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuality() {
        
        quality_ = 0;
        onChanged();
        return this;
      }

      private int imgWidth_ ;
      /**
       * <code>int32 img_width = 6;</code>
       * @return The imgWidth.
       */
      @java.lang.Override
      public int getImgWidth() {
        return imgWidth_;
      }
      /**
       * <code>int32 img_width = 6;</code>
       * @param value The imgWidth to set.
       * @return This builder for chaining.
       */
      public Builder setImgWidth(int value) {
        
        imgWidth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 img_width = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearImgWidth() {
        
        imgWidth_ = 0;
        onChanged();
        return this;
      }

      private int imgHeight_ ;
      /**
       * <code>int32 img_height = 7;</code>
       * @return The imgHeight.
       */
      @java.lang.Override
      public int getImgHeight() {
        return imgHeight_;
      }
      /**
       * <code>int32 img_height = 7;</code>
       * @param value The imgHeight to set.
       * @return This builder for chaining.
       */
      public Builder setImgHeight(int value) {
        
        imgHeight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 img_height = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearImgHeight() {
        
        imgHeight_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Level2)
    }

    // @@protoc_insertion_point(class_scope:Level2)
    private static final Level2OuterClass.Level2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Level2OuterClass.Level2();
    }

    public static Level2OuterClass.Level2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Level2>
        PARSER = new com.google.protobuf.AbstractParser<Level2>() {
      @java.lang.Override
      public Level2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Level2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Level2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Level2> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Level2OuterClass.Level2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Level2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Level2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Level2.proto\"s\n\006Level2\022\t\n\001x\030\001 \001(\005\022\t\n\001y" +
      "\030\002 \001(\005\022\014\n\004type\030\003 \001(\005\022\r\n\005angle\030\004 \001(\002\022\017\n\007q" +
      "uality\030\005 \001(\005\022\021\n\timg_width\030\006 \001(\005\022\022\n\nimg_h" +
      "eight\030\007 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Level2_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Level2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Level2_descriptor,
        new java.lang.String[] { "X", "Y", "Type", "Angle", "Quality", "ImgWidth", "ImgHeight", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
