package Futronic.openFinger;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VerificationRequest.proto

public final class VerificationRequestOuterClass {
  private VerificationRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VerificationRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VerificationRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Fingerprint fingerprint = 1;</code>
     * @return Whether the fingerprint field is set.
     */
    boolean hasFingerprint();
    /**
     * <code>.Fingerprint fingerprint = 1;</code>
     * @return The fingerprint.
     */
    FingerprintOuterClass.Fingerprint getFingerprint();
    /**
     * <code>.Fingerprint fingerprint = 1;</code>
     */
    FingerprintOuterClass.FingerprintOrBuilder getFingerprintOrBuilder();

    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    java.util.List<Level2VectorOuterClass.Level2Vector> 
        getLevel2VectorsList();
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    Level2VectorOuterClass.Level2Vector getLevel2Vectors(int index);
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    int getLevel2VectorsCount();
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    java.util.List<? extends Level2VectorOuterClass.Level2VectorOrBuilder> 
        getLevel2VectorsOrBuilderList();
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    Level2VectorOuterClass.Level2VectorOrBuilder getLevel2VectorsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code VerificationRequest}
   */
  public static final class VerificationRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VerificationRequest)
      VerificationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VerificationRequest.newBuilder() to construct.
    private VerificationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VerificationRequest() {
      level2Vectors_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VerificationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VerificationRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              FingerprintOuterClass.Fingerprint.Builder subBuilder = null;
              if (fingerprint_ != null) {
                subBuilder = fingerprint_.toBuilder();
              }
              fingerprint_ = input.readMessage(FingerprintOuterClass.Fingerprint.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fingerprint_);
                fingerprint_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                level2Vectors_ = new java.util.ArrayList<Level2VectorOuterClass.Level2Vector>();
                mutable_bitField0_ |= 0x00000001;
              }
              level2Vectors_.add(
                  input.readMessage(Level2VectorOuterClass.Level2Vector.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          level2Vectors_ = java.util.Collections.unmodifiableList(level2Vectors_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VerificationRequestOuterClass.internal_static_VerificationRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VerificationRequestOuterClass.internal_static_VerificationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              VerificationRequestOuterClass.VerificationRequest.class, VerificationRequestOuterClass.VerificationRequest.Builder.class);
    }

    public static final int FINGERPRINT_FIELD_NUMBER = 1;
    private FingerprintOuterClass.Fingerprint fingerprint_;
    /**
     * <code>.Fingerprint fingerprint = 1;</code>
     * @return Whether the fingerprint field is set.
     */
    @java.lang.Override
    public boolean hasFingerprint() {
      return fingerprint_ != null;
    }
    /**
     * <code>.Fingerprint fingerprint = 1;</code>
     * @return The fingerprint.
     */
    @java.lang.Override
    public FingerprintOuterClass.Fingerprint getFingerprint() {
      return fingerprint_ == null ? FingerprintOuterClass.Fingerprint.getDefaultInstance() : fingerprint_;
    }
    /**
     * <code>.Fingerprint fingerprint = 1;</code>
     */
    @java.lang.Override
    public FingerprintOuterClass.FingerprintOrBuilder getFingerprintOrBuilder() {
      return getFingerprint();
    }

    public static final int LEVEL2VECTORS_FIELD_NUMBER = 2;
    private java.util.List<Level2VectorOuterClass.Level2Vector> level2Vectors_;
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    @java.lang.Override
    public java.util.List<Level2VectorOuterClass.Level2Vector> getLevel2VectorsList() {
      return level2Vectors_;
    }
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Level2VectorOuterClass.Level2VectorOrBuilder> 
        getLevel2VectorsOrBuilderList() {
      return level2Vectors_;
    }
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    @java.lang.Override
    public int getLevel2VectorsCount() {
      return level2Vectors_.size();
    }
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    @java.lang.Override
    public Level2VectorOuterClass.Level2Vector getLevel2Vectors(int index) {
      return level2Vectors_.get(index);
    }
    /**
     * <code>repeated .Level2Vector level2vectors = 2;</code>
     */
    @java.lang.Override
    public Level2VectorOuterClass.Level2VectorOrBuilder getLevel2VectorsOrBuilder(
        int index) {
      return level2Vectors_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fingerprint_ != null) {
        output.writeMessage(1, getFingerprint());
      }
      for (int i = 0; i < level2Vectors_.size(); i++) {
        output.writeMessage(2, level2Vectors_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fingerprint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFingerprint());
      }
      for (int i = 0; i < level2Vectors_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, level2Vectors_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof VerificationRequestOuterClass.VerificationRequest)) {
        return super.equals(obj);
      }
      VerificationRequestOuterClass.VerificationRequest other = (VerificationRequestOuterClass.VerificationRequest) obj;

      if (hasFingerprint() != other.hasFingerprint()) return false;
      if (hasFingerprint()) {
        if (!getFingerprint()
            .equals(other.getFingerprint())) return false;
      }
      if (!getLevel2VectorsList()
          .equals(other.getLevel2VectorsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFingerprint()) {
        hash = (37 * hash) + FINGERPRINT_FIELD_NUMBER;
        hash = (53 * hash) + getFingerprint().hashCode();
      }
      if (getLevel2VectorsCount() > 0) {
        hash = (37 * hash) + LEVEL2VECTORS_FIELD_NUMBER;
        hash = (53 * hash) + getLevel2VectorsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static VerificationRequestOuterClass.VerificationRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(VerificationRequestOuterClass.VerificationRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VerificationRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VerificationRequest)
        VerificationRequestOuterClass.VerificationRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return VerificationRequestOuterClass.internal_static_VerificationRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return VerificationRequestOuterClass.internal_static_VerificationRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                VerificationRequestOuterClass.VerificationRequest.class, VerificationRequestOuterClass.VerificationRequest.Builder.class);
      }

      // Construct using Futronic.openFinger.VerificationRequestOuterClass.VerificationRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getLevel2VectorsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fingerprintBuilder_ == null) {
          fingerprint_ = null;
        } else {
          fingerprint_ = null;
          fingerprintBuilder_ = null;
        }
        if (level2VectorsBuilder_ == null) {
          level2Vectors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          level2VectorsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return VerificationRequestOuterClass.internal_static_VerificationRequest_descriptor;
      }

      @java.lang.Override
      public VerificationRequestOuterClass.VerificationRequest getDefaultInstanceForType() {
        return VerificationRequestOuterClass.VerificationRequest.getDefaultInstance();
      }

      @java.lang.Override
      public VerificationRequestOuterClass.VerificationRequest build() {
        VerificationRequestOuterClass.VerificationRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public VerificationRequestOuterClass.VerificationRequest buildPartial() {
        VerificationRequestOuterClass.VerificationRequest result = new VerificationRequestOuterClass.VerificationRequest(this);
        int from_bitField0_ = bitField0_;
        if (fingerprintBuilder_ == null) {
          result.fingerprint_ = fingerprint_;
        } else {
          result.fingerprint_ = fingerprintBuilder_.build();
        }
        if (level2VectorsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            level2Vectors_ = java.util.Collections.unmodifiableList(level2Vectors_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.level2Vectors_ = level2Vectors_;
        } else {
          result.level2Vectors_ = level2VectorsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof VerificationRequestOuterClass.VerificationRequest) {
          return mergeFrom((VerificationRequestOuterClass.VerificationRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(VerificationRequestOuterClass.VerificationRequest other) {
        if (other == VerificationRequestOuterClass.VerificationRequest.getDefaultInstance()) return this;
        if (other.hasFingerprint()) {
          mergeFingerprint(other.getFingerprint());
        }
        if (level2VectorsBuilder_ == null) {
          if (!other.level2Vectors_.isEmpty()) {
            if (level2Vectors_.isEmpty()) {
              level2Vectors_ = other.level2Vectors_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureLevel2VectorsIsMutable();
              level2Vectors_.addAll(other.level2Vectors_);
            }
            onChanged();
          }
        } else {
          if (!other.level2Vectors_.isEmpty()) {
            if (level2VectorsBuilder_.isEmpty()) {
              level2VectorsBuilder_.dispose();
              level2VectorsBuilder_ = null;
              level2Vectors_ = other.level2Vectors_;
              bitField0_ = (bitField0_ & ~0x00000001);
              level2VectorsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getLevel2VectorsFieldBuilder() : null;
            } else {
              level2VectorsBuilder_.addAllMessages(other.level2Vectors_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        VerificationRequestOuterClass.VerificationRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (VerificationRequestOuterClass.VerificationRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private FingerprintOuterClass.Fingerprint fingerprint_;
      private com.google.protobuf.SingleFieldBuilderV3<
          FingerprintOuterClass.Fingerprint, FingerprintOuterClass.Fingerprint.Builder, FingerprintOuterClass.FingerprintOrBuilder> fingerprintBuilder_;
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       * @return Whether the fingerprint field is set.
       */
      public boolean hasFingerprint() {
        return fingerprintBuilder_ != null || fingerprint_ != null;
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       * @return The fingerprint.
       */
      public FingerprintOuterClass.Fingerprint getFingerprint() {
        if (fingerprintBuilder_ == null) {
          return fingerprint_ == null ? FingerprintOuterClass.Fingerprint.getDefaultInstance() : fingerprint_;
        } else {
          return fingerprintBuilder_.getMessage();
        }
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       */
      public Builder setFingerprint(FingerprintOuterClass.Fingerprint value) {
        if (fingerprintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fingerprint_ = value;
          onChanged();
        } else {
          fingerprintBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       */
      public Builder setFingerprint(
          FingerprintOuterClass.Fingerprint.Builder builderForValue) {
        if (fingerprintBuilder_ == null) {
          fingerprint_ = builderForValue.build();
          onChanged();
        } else {
          fingerprintBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       */
      public Builder mergeFingerprint(FingerprintOuterClass.Fingerprint value) {
        if (fingerprintBuilder_ == null) {
          if (fingerprint_ != null) {
            fingerprint_ =
              FingerprintOuterClass.Fingerprint.newBuilder(fingerprint_).mergeFrom(value).buildPartial();
          } else {
            fingerprint_ = value;
          }
          onChanged();
        } else {
          fingerprintBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       */
      public Builder clearFingerprint() {
        if (fingerprintBuilder_ == null) {
          fingerprint_ = null;
          onChanged();
        } else {
          fingerprint_ = null;
          fingerprintBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       */
      public FingerprintOuterClass.Fingerprint.Builder getFingerprintBuilder() {
        
        onChanged();
        return getFingerprintFieldBuilder().getBuilder();
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       */
      public FingerprintOuterClass.FingerprintOrBuilder getFingerprintOrBuilder() {
        if (fingerprintBuilder_ != null) {
          return fingerprintBuilder_.getMessageOrBuilder();
        } else {
          return fingerprint_ == null ?
              FingerprintOuterClass.Fingerprint.getDefaultInstance() : fingerprint_;
        }
      }
      /**
       * <code>.Fingerprint fingerprint = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FingerprintOuterClass.Fingerprint, FingerprintOuterClass.Fingerprint.Builder, FingerprintOuterClass.FingerprintOrBuilder> 
          getFingerprintFieldBuilder() {
        if (fingerprintBuilder_ == null) {
          fingerprintBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FingerprintOuterClass.Fingerprint, FingerprintOuterClass.Fingerprint.Builder, FingerprintOuterClass.FingerprintOrBuilder>(
                  getFingerprint(),
                  getParentForChildren(),
                  isClean());
          fingerprint_ = null;
        }
        return fingerprintBuilder_;
      }

      private java.util.List<Level2VectorOuterClass.Level2Vector> level2Vectors_ =
        java.util.Collections.emptyList();
      private void ensureLevel2VectorsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          level2Vectors_ = new java.util.ArrayList<Level2VectorOuterClass.Level2Vector>(level2Vectors_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Level2VectorOuterClass.Level2Vector, Level2VectorOuterClass.Level2Vector.Builder, Level2VectorOuterClass.Level2VectorOrBuilder> level2VectorsBuilder_;

      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public java.util.List<Level2VectorOuterClass.Level2Vector> getLevel2VectorsList() {
        if (level2VectorsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(level2Vectors_);
        } else {
          return level2VectorsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public int getLevel2VectorsCount() {
        if (level2VectorsBuilder_ == null) {
          return level2Vectors_.size();
        } else {
          return level2VectorsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Level2VectorOuterClass.Level2Vector getLevel2Vectors(int index) {
        if (level2VectorsBuilder_ == null) {
          return level2Vectors_.get(index);
        } else {
          return level2VectorsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder setLevel2Vectors(
          int index, Level2VectorOuterClass.Level2Vector value) {
        if (level2VectorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLevel2VectorsIsMutable();
          level2Vectors_.set(index, value);
          onChanged();
        } else {
          level2VectorsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder setLevel2Vectors(
          int index, Level2VectorOuterClass.Level2Vector.Builder builderForValue) {
        if (level2VectorsBuilder_ == null) {
          ensureLevel2VectorsIsMutable();
          level2Vectors_.set(index, builderForValue.build());
          onChanged();
        } else {
          level2VectorsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder addLevel2Vectors(Level2VectorOuterClass.Level2Vector value) {
        if (level2VectorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLevel2VectorsIsMutable();
          level2Vectors_.add(value);
          onChanged();
        } else {
          level2VectorsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder addLevel2Vectors(
          int index, Level2VectorOuterClass.Level2Vector value) {
        if (level2VectorsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLevel2VectorsIsMutable();
          level2Vectors_.add(index, value);
          onChanged();
        } else {
          level2VectorsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder addLevel2Vectors(
          Level2VectorOuterClass.Level2Vector.Builder builderForValue) {
        if (level2VectorsBuilder_ == null) {
          ensureLevel2VectorsIsMutable();
          level2Vectors_.add(builderForValue.build());
          onChanged();
        } else {
          level2VectorsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder addLevel2Vectors(
          int index, Level2VectorOuterClass.Level2Vector.Builder builderForValue) {
        if (level2VectorsBuilder_ == null) {
          ensureLevel2VectorsIsMutable();
          level2Vectors_.add(index, builderForValue.build());
          onChanged();
        } else {
          level2VectorsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder addAllLevel2Vectors(
          java.lang.Iterable<? extends Level2VectorOuterClass.Level2Vector> values) {
        if (level2VectorsBuilder_ == null) {
          ensureLevel2VectorsIsMutable();
          addAll(
              values, level2Vectors_);
          onChanged();
        } else {
          level2VectorsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder clearLevel2Vectors() {
        if (level2VectorsBuilder_ == null) {
          level2Vectors_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          level2VectorsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Builder removeLevel2Vectors(int index) {
        if (level2VectorsBuilder_ == null) {
          ensureLevel2VectorsIsMutable();
          level2Vectors_.remove(index);
          onChanged();
        } else {
          level2VectorsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Level2VectorOuterClass.Level2Vector.Builder getLevel2VectorsBuilder(
          int index) {
        return getLevel2VectorsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Level2VectorOuterClass.Level2VectorOrBuilder getLevel2VectorsOrBuilder(
          int index) {
        if (level2VectorsBuilder_ == null) {
          return level2Vectors_.get(index);  } else {
          return level2VectorsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public java.util.List<? extends Level2VectorOuterClass.Level2VectorOrBuilder> 
           getLevel2VectorsOrBuilderList() {
        if (level2VectorsBuilder_ != null) {
          return level2VectorsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(level2Vectors_);
        }
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Level2VectorOuterClass.Level2Vector.Builder addLevel2VectorsBuilder() {
        return getLevel2VectorsFieldBuilder().addBuilder(
            Level2VectorOuterClass.Level2Vector.getDefaultInstance());
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public Level2VectorOuterClass.Level2Vector.Builder addLevel2VectorsBuilder(
          int index) {
        return getLevel2VectorsFieldBuilder().addBuilder(
            index, Level2VectorOuterClass.Level2Vector.getDefaultInstance());
      }
      /**
       * <code>repeated .Level2Vector level2vectors = 2;</code>
       */
      public java.util.List<Level2VectorOuterClass.Level2Vector.Builder> 
           getLevel2VectorsBuilderList() {
        return getLevel2VectorsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Level2VectorOuterClass.Level2Vector, Level2VectorOuterClass.Level2Vector.Builder, Level2VectorOuterClass.Level2VectorOrBuilder> 
          getLevel2VectorsFieldBuilder() {
        if (level2VectorsBuilder_ == null) {
          level2VectorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Level2VectorOuterClass.Level2Vector, Level2VectorOuterClass.Level2Vector.Builder, Level2VectorOuterClass.Level2VectorOrBuilder>(
                  level2Vectors_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          level2Vectors_ = null;
        }
        return level2VectorsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:VerificationRequest)
    }

    // @@protoc_insertion_point(class_scope:VerificationRequest)
    private static final VerificationRequestOuterClass.VerificationRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new VerificationRequestOuterClass.VerificationRequest();
    }

    public static VerificationRequestOuterClass.VerificationRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VerificationRequest>
        PARSER = new com.google.protobuf.AbstractParser<VerificationRequest>() {
      @java.lang.Override
      public VerificationRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VerificationRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VerificationRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VerificationRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public VerificationRequestOuterClass.VerificationRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VerificationRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VerificationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031VerificationRequest.proto\032\021Fingerprint" +
      ".proto\032\022Level2Vector.proto\"^\n\023Verificati" +
      "onRequest\022!\n\013fingerprint\030\001 \001(\0132\014.Fingerp" +
      "rint\022$\n\rlevel2vectors\030\002 \003(\0132\r.Level2Vect" +
      "orb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          FingerprintOuterClass.getDescriptor(),
          Level2VectorOuterClass.getDescriptor(),
        });
    internal_static_VerificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VerificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VerificationRequest_descriptor,
        new java.lang.String[] { "Fingerprint", "Level2Vectors", });
    FingerprintOuterClass.getDescriptor();
    Level2VectorOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
