// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: openfinger.proto

package Futronic;

public final class Openfinger {
  private Openfinger() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FingerprintOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.Fingerprint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <pre>
     * 500 ppi or 1000 ppi
     * </pre>
     *
     * <code>int32 resolution = 3;</code>
     * @return The resolution.
     */
    int getResolution();

    /**
     * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
     * @return The enum numeric value on the wire for color.
     */
    int getColorValue();
    /**
     * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
     * @return The color.
     */
    Openfinger.Fingerprint.Colorspace getColor();

    /**
     * <pre>
     * image data
     * </pre>
     *
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * message specifying the fingerprint image
   * </pre>
   *
   * Protobuf type {@code OpenFinger.Fingerprint}
   */
  public static final class Fingerprint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.Fingerprint)
      FingerprintOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Fingerprint.newBuilder() to construct.
    private Fingerprint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Fingerprint() {
      color_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Fingerprint();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Fingerprint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              width_ = input.readInt32();
              break;
            }
            case 16: {

              height_ = input.readInt32();
              break;
            }
            case 24: {

              resolution_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              color_ = rawValue;
              break;
            }
            case 42: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openfinger.internal_static_OpenFinger_Fingerprint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openfinger.internal_static_OpenFinger_Fingerprint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Openfinger.Fingerprint.class, Openfinger.Fingerprint.Builder.class);
    }

    /**
     * <pre>
     * informs about the image color space
     * </pre>
     *
     * Protobuf enum {@code OpenFinger.Fingerprint.Colorspace}
     */
    public enum Colorspace
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>GRAYSCALE = 0;</code>
       */
      GRAYSCALE(0),
      /**
       * <code>RGB = 1;</code>
       */
      RGB(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>GRAYSCALE = 0;</code>
       */
      public static final int GRAYSCALE_VALUE = 0;
      /**
       * <code>RGB = 1;</code>
       */
      public static final int RGB_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Colorspace valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Colorspace forNumber(int value) {
        switch (value) {
          case 0: return GRAYSCALE;
          case 1: return RGB;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Colorspace>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Colorspace> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Colorspace>() {
              public Colorspace findValueByNumber(int number) {
                return Colorspace.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Openfinger.Fingerprint.getDescriptor().getEnumTypes().get(0);
      }

      private static final Colorspace[] VALUES = values();

      public static Colorspace valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Colorspace(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:OpenFinger.Fingerprint.Colorspace)
    }

    public static final int WIDTH_FIELD_NUMBER = 1;
    private int width_;
    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <pre>
     * in px
     * </pre>
     *
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int RESOLUTION_FIELD_NUMBER = 3;
    private int resolution_;
    /**
     * <pre>
     * 500 ppi or 1000 ppi
     * </pre>
     *
     * <code>int32 resolution = 3;</code>
     * @return The resolution.
     */
    @java.lang.Override
    public int getResolution() {
      return resolution_;
    }

    public static final int COLOR_FIELD_NUMBER = 4;
    private int color_;
    /**
     * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
     * @return The enum numeric value on the wire for color.
     */
    @java.lang.Override public int getColorValue() {
      return color_;
    }
    /**
     * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
     * @return The color.
     */
    @java.lang.Override public Openfinger.Fingerprint.Colorspace getColor() {
      @SuppressWarnings("deprecation")
      Openfinger.Fingerprint.Colorspace result = Openfinger.Fingerprint.Colorspace.valueOf(color_);
      return result == null ? Openfinger.Fingerprint.Colorspace.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * image data
     * </pre>
     *
     * <code>bytes data = 5;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (width_ != 0) {
        output.writeInt32(1, width_);
      }
      if (height_ != 0) {
        output.writeInt32(2, height_);
      }
      if (resolution_ != 0) {
        output.writeInt32(3, resolution_);
      }
      if (color_ != Openfinger.Fingerprint.Colorspace.GRAYSCALE.getNumber()) {
        output.writeEnum(4, color_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (resolution_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, resolution_);
      }
      if (color_ != Openfinger.Fingerprint.Colorspace.GRAYSCALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, color_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Openfinger.Fingerprint)) {
        return super.equals(obj);
      }
      Openfinger.Fingerprint other = (Openfinger.Fingerprint) obj;

      if (getWidth()
          != other.getWidth()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getResolution()
          != other.getResolution()) return false;
      if (color_ != other.color_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + RESOLUTION_FIELD_NUMBER;
      hash = (53 * hash) + getResolution();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + color_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Openfinger.Fingerprint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.Fingerprint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.Fingerprint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.Fingerprint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.Fingerprint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.Fingerprint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.Fingerprint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Openfinger.Fingerprint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Openfinger.Fingerprint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Openfinger.Fingerprint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Openfinger.Fingerprint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Openfinger.Fingerprint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Openfinger.Fingerprint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message specifying the fingerprint image
     * </pre>
     *
     * Protobuf type {@code OpenFinger.Fingerprint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.Fingerprint)
        Openfinger.FingerprintOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Openfinger.internal_static_OpenFinger_Fingerprint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Openfinger.internal_static_OpenFinger_Fingerprint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Openfinger.Fingerprint.class, Openfinger.Fingerprint.Builder.class);
      }

      // Construct using Futronic.Openfinger.Fingerprint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        width_ = 0;

        height_ = 0;

        resolution_ = 0;

        color_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openfinger.internal_static_OpenFinger_Fingerprint_descriptor;
      }

      @java.lang.Override
      public Openfinger.Fingerprint getDefaultInstanceForType() {
        return Openfinger.Fingerprint.getDefaultInstance();
      }

      @java.lang.Override
      public Openfinger.Fingerprint build() {
        Openfinger.Fingerprint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Openfinger.Fingerprint buildPartial() {
        Openfinger.Fingerprint result = new Openfinger.Fingerprint(this);
        result.width_ = width_;
        result.height_ = height_;
        result.resolution_ = resolution_;
        result.color_ = color_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openfinger.Fingerprint) {
          return mergeFrom((Openfinger.Fingerprint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Openfinger.Fingerprint other) {
        if (other == Openfinger.Fingerprint.getDefaultInstance()) return this;
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getResolution() != 0) {
          setResolution(other.getResolution());
        }
        if (other.color_ != 0) {
          setColorValue(other.getColorValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Openfinger.Fingerprint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Openfinger.Fingerprint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int width_ ;
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 width = 1;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 width = 1;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 width = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 height = 2;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 height = 2;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * in px
       * </pre>
       *
       * <code>int32 height = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private int resolution_ ;
      /**
       * <pre>
       * 500 ppi or 1000 ppi
       * </pre>
       *
       * <code>int32 resolution = 3;</code>
       * @return The resolution.
       */
      @java.lang.Override
      public int getResolution() {
        return resolution_;
      }
      /**
       * <pre>
       * 500 ppi or 1000 ppi
       * </pre>
       *
       * <code>int32 resolution = 3;</code>
       * @param value The resolution to set.
       * @return This builder for chaining.
       */
      public Builder setResolution(int value) {
        
        resolution_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 500 ppi or 1000 ppi
       * </pre>
       *
       * <code>int32 resolution = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResolution() {
        
        resolution_ = 0;
        onChanged();
        return this;
      }

      private int color_ = 0;
      /**
       * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
       * @return The enum numeric value on the wire for color.
       */
      @java.lang.Override public int getColorValue() {
        return color_;
      }
      /**
       * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
       * @param value The enum numeric value on the wire for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorValue(int value) {
        
        color_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
       * @return The color.
       */
      @java.lang.Override
      public Openfinger.Fingerprint.Colorspace getColor() {
        @SuppressWarnings("deprecation")
        Openfinger.Fingerprint.Colorspace result = Openfinger.Fingerprint.Colorspace.valueOf(color_);
        return result == null ? Openfinger.Fingerprint.Colorspace.UNRECOGNIZED : result;
      }
      /**
       * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(Openfinger.Fingerprint.Colorspace value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        color_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.OpenFinger.Fingerprint.Colorspace color = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        
        color_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * image data
       * </pre>
       *
       * <code>bytes data = 5;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * image data
       * </pre>
       *
       * <code>bytes data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * image data
       * </pre>
       *
       * <code>bytes data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.Fingerprint)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.Fingerprint)
    private static final Openfinger.Fingerprint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Openfinger.Fingerprint();
    }

    public static Openfinger.Fingerprint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Fingerprint>
        PARSER = new com.google.protobuf.AbstractParser<Fingerprint>() {
      @java.lang.Override
      public Fingerprint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Fingerprint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Fingerprint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Fingerprint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Openfinger.Fingerprint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PreprocessingRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.PreprocessingRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * TODO: fields representing preprocessing parameters
     * </pre>
     *
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return Whether the fingerprint field is set.
     */
    boolean hasFingerprint();
    /**
     * <pre>
     * TODO: fields representing preprocessing parameters
     * </pre>
     *
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return The fingerprint.
     */
    Openfinger.Fingerprint getFingerprint();
    /**
     * <pre>
     * TODO: fields representing preprocessing parameters
     * </pre>
     *
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     */
    Openfinger.FingerprintOrBuilder getFingerprintOrBuilder();
  }
  /**
   * <pre>
   * message specifying preprocessing OpenFinger request
   * </pre>
   *
   * Protobuf type {@code OpenFinger.PreprocessingRequest}
   */
  public static final class PreprocessingRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.PreprocessingRequest)
      PreprocessingRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PreprocessingRequest.newBuilder() to construct.
    private PreprocessingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PreprocessingRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PreprocessingRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PreprocessingRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              Openfinger.Fingerprint.Builder subBuilder = null;
              if (fingerprint_ != null) {
                subBuilder = fingerprint_.toBuilder();
              }
              fingerprint_ = input.readMessage(Openfinger.Fingerprint.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fingerprint_);
                fingerprint_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openfinger.internal_static_OpenFinger_PreprocessingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openfinger.internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Openfinger.PreprocessingRequest.class, Openfinger.PreprocessingRequest.Builder.class);
    }

    public static final int FINGERPRINT_FIELD_NUMBER = 1;
    private Openfinger.Fingerprint fingerprint_;
    /**
     * <pre>
     * TODO: fields representing preprocessing parameters
     * </pre>
     *
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return Whether the fingerprint field is set.
     */
    @java.lang.Override
    public boolean hasFingerprint() {
      return fingerprint_ != null;
    }
    /**
     * <pre>
     * TODO: fields representing preprocessing parameters
     * </pre>
     *
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     * @return The fingerprint.
     */
    @java.lang.Override
    public Openfinger.Fingerprint getFingerprint() {
      return fingerprint_ == null ? Openfinger.Fingerprint.getDefaultInstance() : fingerprint_;
    }
    /**
     * <pre>
     * TODO: fields representing preprocessing parameters
     * </pre>
     *
     * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
     */
    @java.lang.Override
    public Openfinger.FingerprintOrBuilder getFingerprintOrBuilder() {
      return getFingerprint();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (fingerprint_ != null) {
        output.writeMessage(1, getFingerprint());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (fingerprint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFingerprint());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Openfinger.PreprocessingRequest)) {
        return super.equals(obj);
      }
      Openfinger.PreprocessingRequest other = (Openfinger.PreprocessingRequest) obj;

      if (hasFingerprint() != other.hasFingerprint()) return false;
      if (hasFingerprint()) {
        if (!getFingerprint()
            .equals(other.getFingerprint())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFingerprint()) {
        hash = (37 * hash) + FINGERPRINT_FIELD_NUMBER;
        hash = (53 * hash) + getFingerprint().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Openfinger.PreprocessingRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.PreprocessingRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.PreprocessingRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.PreprocessingRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.PreprocessingRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.PreprocessingRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.PreprocessingRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Openfinger.PreprocessingRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Openfinger.PreprocessingRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Openfinger.PreprocessingRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Openfinger.PreprocessingRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Openfinger.PreprocessingRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Openfinger.PreprocessingRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message specifying preprocessing OpenFinger request
     * </pre>
     *
     * Protobuf type {@code OpenFinger.PreprocessingRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.PreprocessingRequest)
        Openfinger.PreprocessingRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Openfinger.internal_static_OpenFinger_PreprocessingRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Openfinger.internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Openfinger.PreprocessingRequest.class, Openfinger.PreprocessingRequest.Builder.class);
      }

      // Construct using Futronic.Openfinger.PreprocessingRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fingerprintBuilder_ == null) {
          fingerprint_ = null;
        } else {
          fingerprint_ = null;
          fingerprintBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openfinger.internal_static_OpenFinger_PreprocessingRequest_descriptor;
      }

      @java.lang.Override
      public Openfinger.PreprocessingRequest getDefaultInstanceForType() {
        return Openfinger.PreprocessingRequest.getDefaultInstance();
      }

      @java.lang.Override
      public Openfinger.PreprocessingRequest build() {
        Openfinger.PreprocessingRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Openfinger.PreprocessingRequest buildPartial() {
        Openfinger.PreprocessingRequest result = new Openfinger.PreprocessingRequest(this);
        if (fingerprintBuilder_ == null) {
          result.fingerprint_ = fingerprint_;
        } else {
          result.fingerprint_ = fingerprintBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openfinger.PreprocessingRequest) {
          return mergeFrom((Openfinger.PreprocessingRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Openfinger.PreprocessingRequest other) {
        if (other == Openfinger.PreprocessingRequest.getDefaultInstance()) return this;
        if (other.hasFingerprint()) {
          mergeFingerprint(other.getFingerprint());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Openfinger.PreprocessingRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Openfinger.PreprocessingRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Openfinger.Fingerprint fingerprint_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Openfinger.Fingerprint, Openfinger.Fingerprint.Builder, Openfinger.FingerprintOrBuilder> fingerprintBuilder_;
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       * @return Whether the fingerprint field is set.
       */
      public boolean hasFingerprint() {
        return fingerprintBuilder_ != null || fingerprint_ != null;
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       * @return The fingerprint.
       */
      public Openfinger.Fingerprint getFingerprint() {
        if (fingerprintBuilder_ == null) {
          return fingerprint_ == null ? Openfinger.Fingerprint.getDefaultInstance() : fingerprint_;
        } else {
          return fingerprintBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder setFingerprint(Openfinger.Fingerprint value) {
        if (fingerprintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fingerprint_ = value;
          onChanged();
        } else {
          fingerprintBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder setFingerprint(
          Openfinger.Fingerprint.Builder builderForValue) {
        if (fingerprintBuilder_ == null) {
          fingerprint_ = builderForValue.build();
          onChanged();
        } else {
          fingerprintBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder mergeFingerprint(Openfinger.Fingerprint value) {
        if (fingerprintBuilder_ == null) {
          if (fingerprint_ != null) {
            fingerprint_ =
              Openfinger.Fingerprint.newBuilder(fingerprint_).mergeFrom(value).buildPartial();
          } else {
            fingerprint_ = value;
          }
          onChanged();
        } else {
          fingerprintBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Builder clearFingerprint() {
        if (fingerprintBuilder_ == null) {
          fingerprint_ = null;
          onChanged();
        } else {
          fingerprint_ = null;
          fingerprintBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Openfinger.Fingerprint.Builder getFingerprintBuilder() {
        
        onChanged();
        return getFingerprintFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      public Openfinger.FingerprintOrBuilder getFingerprintOrBuilder() {
        if (fingerprintBuilder_ != null) {
          return fingerprintBuilder_.getMessageOrBuilder();
        } else {
          return fingerprint_ == null ?
              Openfinger.Fingerprint.getDefaultInstance() : fingerprint_;
        }
      }
      /**
       * <pre>
       * TODO: fields representing preprocessing parameters
       * </pre>
       *
       * <code>.OpenFinger.Fingerprint fingerprint = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Openfinger.Fingerprint, Openfinger.Fingerprint.Builder, Openfinger.FingerprintOrBuilder>
          getFingerprintFieldBuilder() {
        if (fingerprintBuilder_ == null) {
          fingerprintBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Openfinger.Fingerprint, Openfinger.Fingerprint.Builder, Openfinger.FingerprintOrBuilder>(
                  getFingerprint(),
                  getParentForChildren(),
                  isClean());
          fingerprint_ = null;
        }
        return fingerprintBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.PreprocessingRequest)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.PreprocessingRequest)
    private static final Openfinger.PreprocessingRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Openfinger.PreprocessingRequest();
    }

    public static Openfinger.PreprocessingRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PreprocessingRequest>
        PARSER = new com.google.protobuf.AbstractParser<PreprocessingRequest>() {
      @java.lang.Override
      public PreprocessingRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PreprocessingRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PreprocessingRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PreprocessingRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Openfinger.PreprocessingRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PreprocessingResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OpenFinger.PreprocessingResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    java.util.List<Openfinger.Fingerprint>
        getResultsList();
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    Openfinger.Fingerprint getResults(int index);
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    int getResultsCount();
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    java.util.List<? extends Openfinger.FingerprintOrBuilder>
        getResultsOrBuilderList();
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    Openfinger.FingerprintOrBuilder getResultsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * message specifying preprocessing OpenFinger response
   * </pre>
   *
   * Protobuf type {@code OpenFinger.PreprocessingResponse}
   */
  public static final class PreprocessingResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OpenFinger.PreprocessingResponse)
      PreprocessingResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PreprocessingResponse.newBuilder() to construct.
    private PreprocessingResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PreprocessingResponse() {
      results_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PreprocessingResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PreprocessingResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                results_ = new java.util.ArrayList<Openfinger.Fingerprint>();
                mutable_bitField0_ |= 0x00000001;
              }
              results_.add(
                  input.readMessage(Openfinger.Fingerprint.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          results_ = java.util.Collections.unmodifiableList(results_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Openfinger.internal_static_OpenFinger_PreprocessingResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Openfinger.internal_static_OpenFinger_PreprocessingResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Openfinger.PreprocessingResponse.class, Openfinger.PreprocessingResponse.Builder.class);
    }

    public static final int RESULTS_FIELD_NUMBER = 1;
    private java.util.List<Openfinger.Fingerprint> results_;
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    @java.lang.Override
    public java.util.List<Openfinger.Fingerprint> getResultsList() {
      return results_;
    }
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends Openfinger.FingerprintOrBuilder>
        getResultsOrBuilderList() {
      return results_;
    }
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    @java.lang.Override
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    @java.lang.Override
    public Openfinger.Fingerprint getResults(int index) {
      return results_.get(index);
    }
    /**
     * <pre>
     * array of preprocessing results (images after individual processing stages)
     * </pre>
     *
     * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
     */
    @java.lang.Override
    public Openfinger.FingerprintOrBuilder getResultsOrBuilder(
        int index) {
      return results_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < results_.size(); i++) {
        output.writeMessage(1, results_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < results_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, results_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Openfinger.PreprocessingResponse)) {
        return super.equals(obj);
      }
      Openfinger.PreprocessingResponse other = (Openfinger.PreprocessingResponse) obj;

      if (!getResultsList()
          .equals(other.getResultsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getResultsCount() > 0) {
        hash = (37 * hash) + RESULTS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Openfinger.PreprocessingResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.PreprocessingResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.PreprocessingResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.PreprocessingResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.PreprocessingResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Openfinger.PreprocessingResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Openfinger.PreprocessingResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Openfinger.PreprocessingResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Openfinger.PreprocessingResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Openfinger.PreprocessingResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Openfinger.PreprocessingResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Openfinger.PreprocessingResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Openfinger.PreprocessingResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * message specifying preprocessing OpenFinger response
     * </pre>
     *
     * Protobuf type {@code OpenFinger.PreprocessingResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OpenFinger.PreprocessingResponse)
        Openfinger.PreprocessingResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Openfinger.internal_static_OpenFinger_PreprocessingResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Openfinger.internal_static_OpenFinger_PreprocessingResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Openfinger.PreprocessingResponse.class, Openfinger.PreprocessingResponse.Builder.class);
      }

      // Construct using Futronic.Openfinger.PreprocessingResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Openfinger.internal_static_OpenFinger_PreprocessingResponse_descriptor;
      }

      @java.lang.Override
      public Openfinger.PreprocessingResponse getDefaultInstanceForType() {
        return Openfinger.PreprocessingResponse.getDefaultInstance();
      }

      @java.lang.Override
      public Openfinger.PreprocessingResponse build() {
        Openfinger.PreprocessingResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Openfinger.PreprocessingResponse buildPartial() {
        Openfinger.PreprocessingResponse result = new Openfinger.PreprocessingResponse(this);
        int from_bitField0_ = bitField0_;
        if (resultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            results_ = java.util.Collections.unmodifiableList(results_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.results_ = results_;
        } else {
          result.results_ = resultsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Openfinger.PreprocessingResponse) {
          return mergeFrom((Openfinger.PreprocessingResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Openfinger.PreprocessingResponse other) {
        if (other == Openfinger.PreprocessingResponse.getDefaultInstance()) return this;
        if (resultsBuilder_ == null) {
          if (!other.results_.isEmpty()) {
            if (results_.isEmpty()) {
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureResultsIsMutable();
              results_.addAll(other.results_);
            }
            onChanged();
          }
        } else {
          if (!other.results_.isEmpty()) {
            if (resultsBuilder_.isEmpty()) {
              resultsBuilder_.dispose();
              resultsBuilder_ = null;
              results_ = other.results_;
              bitField0_ = (bitField0_ & ~0x00000001);
              resultsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getResultsFieldBuilder() : null;
            } else {
              resultsBuilder_.addAllMessages(other.results_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Openfinger.PreprocessingResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Openfinger.PreprocessingResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<Openfinger.Fingerprint> results_ =
        java.util.Collections.emptyList();
      private void ensureResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          results_ = new java.util.ArrayList<Openfinger.Fingerprint>(results_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Openfinger.Fingerprint, Openfinger.Fingerprint.Builder, Openfinger.FingerprintOrBuilder> resultsBuilder_;

      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public java.util.List<Openfinger.Fingerprint> getResultsList() {
        if (resultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(results_);
        } else {
          return resultsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public int getResultsCount() {
        if (resultsBuilder_ == null) {
          return results_.size();
        } else {
          return resultsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Openfinger.Fingerprint getResults(int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);
        } else {
          return resultsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder setResults(
          int index, Openfinger.Fingerprint value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.set(index, value);
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder setResults(
          int index, Openfinger.Fingerprint.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder addResults(Openfinger.Fingerprint value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder addResults(
          int index, Openfinger.Fingerprint value) {
        if (resultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultsIsMutable();
          results_.add(index, value);
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder addResults(
          Openfinger.Fingerprint.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder addResults(
          int index, Openfinger.Fingerprint.Builder builderForValue) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder addAllResults(
          java.lang.Iterable<? extends Openfinger.Fingerprint> values) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, results_);
          onChanged();
        } else {
          resultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder clearResults() {
        if (resultsBuilder_ == null) {
          results_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          resultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Builder removeResults(int index) {
        if (resultsBuilder_ == null) {
          ensureResultsIsMutable();
          results_.remove(index);
          onChanged();
        } else {
          resultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Openfinger.Fingerprint.Builder getResultsBuilder(
          int index) {
        return getResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Openfinger.FingerprintOrBuilder getResultsOrBuilder(
          int index) {
        if (resultsBuilder_ == null) {
          return results_.get(index);  } else {
          return resultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public java.util.List<? extends Openfinger.FingerprintOrBuilder>
           getResultsOrBuilderList() {
        if (resultsBuilder_ != null) {
          return resultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(results_);
        }
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Openfinger.Fingerprint.Builder addResultsBuilder() {
        return getResultsFieldBuilder().addBuilder(
            Openfinger.Fingerprint.getDefaultInstance());
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public Openfinger.Fingerprint.Builder addResultsBuilder(
          int index) {
        return getResultsFieldBuilder().addBuilder(
            index, Openfinger.Fingerprint.getDefaultInstance());
      }
      /**
       * <pre>
       * array of preprocessing results (images after individual processing stages)
       * </pre>
       *
       * <code>repeated .OpenFinger.Fingerprint results = 1;</code>
       */
      public java.util.List<Openfinger.Fingerprint.Builder>
           getResultsBuilderList() {
        return getResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Openfinger.Fingerprint, Openfinger.Fingerprint.Builder, Openfinger.FingerprintOrBuilder>
          getResultsFieldBuilder() {
        if (resultsBuilder_ == null) {
          resultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Openfinger.Fingerprint, Openfinger.Fingerprint.Builder, Openfinger.FingerprintOrBuilder>(
                  results_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          results_ = null;
        }
        return resultsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OpenFinger.PreprocessingResponse)
    }

    // @@protoc_insertion_point(class_scope:OpenFinger.PreprocessingResponse)
    private static final Openfinger.PreprocessingResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Openfinger.PreprocessingResponse();
    }

    public static Openfinger.PreprocessingResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PreprocessingResponse>
        PARSER = new com.google.protobuf.AbstractParser<PreprocessingResponse>() {
      @java.lang.Override
      public PreprocessingResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PreprocessingResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PreprocessingResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PreprocessingResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Openfinger.PreprocessingResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_Fingerprint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_Fingerprint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_PreprocessingRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OpenFinger_PreprocessingResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OpenFinger_PreprocessingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020openfinger.proto\022\nOpenFinger\"\247\001\n\013Finge" +
      "rprint\022\r\n\005width\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\022\022\n" +
      "\nresolution\030\003 \001(\005\0221\n\005color\030\004 \001(\0162\".OpenF" +
      "inger.Fingerprint.Colorspace\022\014\n\004data\030\005 \001" +
      "(\014\"$\n\nColorspace\022\r\n\tGRAYSCALE\020\000\022\007\n\003RGB\020\001" +
      "\"D\n\024PreprocessingRequest\022,\n\013fingerprint\030" +
      "\001 \001(\0132\027.OpenFinger.Fingerprint\"A\n\025Prepro" +
      "cessingResponse\022(\n\007results\030\001 \003(\0132\027.OpenF" +
      "inger.Fingerprintb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OpenFinger_Fingerprint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OpenFinger_Fingerprint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_Fingerprint_descriptor,
        new java.lang.String[] { "Width", "Height", "Resolution", "Color", "Data", });
    internal_static_OpenFinger_PreprocessingRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OpenFinger_PreprocessingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_PreprocessingRequest_descriptor,
        new java.lang.String[] { "Fingerprint", });
    internal_static_OpenFinger_PreprocessingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_OpenFinger_PreprocessingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OpenFinger_PreprocessingResponse_descriptor,
        new java.lang.String[] { "Results", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
